#!/bin/bash
#banner

printf '<\>
   <\>
      <\>
         <\>
            <\>
               <\>
                 <\>
                   <<>>
                 </>
               </>
            </>
         </>
      </>                 TERMUX HUNTER BD
   </>
</>                  >>>>>>>>>>>>>>>>>>>>>>>>>>>'|lolcat -a -s 99 -d 30
echo '                          WELCOME TO TERMUX'|lolcat -a -s 99 -d 300

clear

printf '\e[032m▉▉▉▉▉
   ▉▉▉▉▉
      ▉▉▉▉▉
         ▉▉▉▉▉
            ▉▉▉▉▉
               ▉▉▉▉
                ▉▉▉▉▉▶
               ▉▉▉▉
            ▉▉▉▉▉
         ▉▉▉▉▉
      ▉▉▉▉▉              TERMUX HUNTER BD
   ▉▉▉▉▉
▉▉▉▉▉                ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉\n\n'
